# 🏦 FinGuard AI — Data Loading

### AI-Powered Financial Fraud Detection & Risk Intelligence Platform

**Notebook:** 01 — Data Loading  
**Project:** FinGuard AI  
**Environment:** Python (FinGuard AI)

---

#### 1. Objective

This notebook establishes the data ingestion and validation layer
for the FinGuard AI financial fraud detection system.

The objectives are:

- Locate and validate the raw dataset
- Inspect dataset structure and schema
- Validate data types
- Detect missing values
- Detect duplicate transactions
- Analyze target-class distribution
- Measure dataset memory usage
- Create a representative sample dataset
- Prepare the dataset for downstream preprocessing

---

#### 2. Machine Learning Objective

The target variable is:

- `0` → Legitimate Transaction
- `1` → Fraudulent Transaction

Because fraud is a rare event, FinGuard AI will focus on
precision, recall, F1-score, PR-AUC, false-positive rate,
and false-negative rate rather than accuracy alone.

---

#### 3. Advanced AI Pipeline

The final FinGuard AI system will combine:

1. Supervised Fraud Classification
2. Anomaly Detection
3. Behavioral Feature Engineering
4. Risk Scoring
5. Explainable AI
6. Flask Prediction API
7. Fraud Intelligence Dashboard
8. GitHub + Render Deployment

#### Core Imports

In [1]:
import os
import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

print("FinGuard AI — Data Loading")
print("=" * 60)
print(f"Python Version : {sys.version.split()[0]}")
print(f"NumPy Version  : {np.__version__}")
print(f"Pandas Version : {pd.__version__}")

FinGuard AI — Data Loading
============================================================
Python Version : 3.11.15
NumPy Version  : 2.4.6
Pandas Version : 3.0.5

#### Project Paths

In [2]:
# ============================================================
# Project Directory Configuration
# ============================================================

PROJECT_ROOT = Path.cwd().parent

DATASET_DIR = PROJECT_ROOT / "Dataset"
RAW_DATA_DIR = DATASET_DIR / "Raw"
PROCESSED_DATA_DIR = DATASET_DIR / "Processed"
SAMPLE_DATA_DIR = DATASET_DIR / "Sample"

REPORTS_DIR = PROJECT_ROOT / "Reports"
FIGURES_DIR = REPORTS_DIR / "Figures"

RAW_DATA_PATH = RAW_DATA_DIR / "creditcard.csv"

print("Project Paths")
print("=" * 60)

print(f"Project Root       : {PROJECT_ROOT}")
print(f"Dataset Directory  : {DATASET_DIR}")
print(f"Raw Dataset        : {RAW_DATA_DIR}")
print(f"Processed Dataset  : {PROCESSED_DATA_DIR}")
print(f"Sample Dataset     : {SAMPLE_DATA_DIR}")
print(f"Raw File           : {RAW_DATA_PATH}")

Project Paths
============================================================
Project Root       : C:\Users\viqua\Desktop\FinGuard AI
Dataset Directory  : C:\Users\viqua\Desktop\FinGuard AI\Dataset
Raw Dataset        : C:\Users\viqua\Desktop\FinGuard AI\Dataset\Raw
Processed Dataset  : C:\Users\viqua\Desktop\FinGuard AI\Dataset\Processed
Sample Dataset     : C:\Users\viqua\Desktop\FinGuard AI\Dataset\Sample
Raw File           : C:\Users\viqua\Desktop\FinGuard AI\Dataset\Raw\creditcard.csv

#### Validate Project Structure

In [3]:
# ============================================================
# Project Structure Validation
# ============================================================

required_directories = [
    DATASET_DIR,
    RAW_DATA_DIR,
    PROCESSED_DATA_DIR,
    SAMPLE_DATA_DIR,
    PROJECT_ROOT / "Models",
    PROJECT_ROOT / "src",
    PROJECT_ROOT / "templates",
    PROJECT_ROOT / "static",
    PROJECT_ROOT / "Reports",
    PROJECT_ROOT / "Tests",
    PROJECT_ROOT / "config",
    PROJECT_ROOT / "api",
]

print("Project Structure Validation")
print("=" * 60)

all_directories_exist = True

for directory in required_directories:
    exists = directory.exists()
    
    if exists:
        status = "✓ EXISTS"
    else:
        status = "✗ MISSING"
        all_directories_exist = False
    
    print(f"{status:<12} {directory.relative_to(PROJECT_ROOT)}")

print("=" * 60)

if all_directories_exist:
    print("✓ Project structure validation PASSED")
else:
    print("⚠ Some project directories are missing")

Project Structure Validation
============================================================
✓ EXISTS     Dataset
✓ EXISTS     Dataset\Raw
✓ EXISTS     Dataset\Processed
✓ EXISTS     Dataset\Sample
✓ EXISTS     Models
✓ EXISTS     src
✓ EXISTS     templates
✓ EXISTS     static
✓ EXISTS     Reports
✓ EXISTS     Tests
✓ EXISTS     config
✓ EXISTS     api
============================================================
✓ Project structure validation PASSED

#### Validate Raw Dataset

In [4]:
# ============================================================
# Raw Dataset Validation
# ============================================================

print("Raw Dataset Validation")
print("=" * 60)

if RAW_DATA_PATH.exists():
    file_size_mb = RAW_DATA_PATH.stat().st_size / (1024 ** 2)
    
    print("✓ Dataset file found")
    print(f"File Name : {RAW_DATA_PATH.name}")
    print(f"File Size : {file_size_mb:.2f} MB")
    print(f"Location  : {RAW_DATA_PATH}")
else:
    raise FileNotFoundError(
        f"Raw dataset not found at:\n{RAW_DATA_PATH}"
    )

Raw Dataset Validation
============================================================
✓ Dataset file found
File Name : creditcard.csv
File Size : 143.84 MB
Location  : C:\Users\viqua\Desktop\FinGuard AI\Dataset\Raw\creditcard.csv

####

#### Discover Raw Files

In [5]:
# ============================================================
# Raw Dataset Directory Inspection
# ============================================================

raw_files = [
    file for file in RAW_DATA_DIR.iterdir()
    if file.is_file()
]

print("Files Found in Dataset/Raw")
print("=" * 60)

for file in raw_files:
    size_mb = file.stat().st_size / (1024 ** 2)
    print(f"{file.name:<30} {size_mb:>10.2f} MB")

print("=" * 60)
print(f"Total files: {len(raw_files)}")

Files Found in Dataset/Raw
============================================================
creditcard.csv                     143.84 MB
============================================================
Total files: 1

#### Inspect Dataset Header

In [6]:
# ============================================================
# Dataset Header Inspection
# ============================================================

header_df = pd.read_csv(
    RAW_DATA_PATH,
    nrows=5
)

print("Dataset Columns")
print("=" * 60)

for index, column in enumerate(header_df.columns, start=1):
    print(f"{index:02d}. {column}")

print("=" * 60)
print(f"Total Columns: {len(header_df.columns)}")

Dataset Columns
============================================================
01. Time
02. V1
03. V2
04. V3
05. V4
06. V5
07. V6
08. V7
09. V8
10. V9
11. V10
12. V11
13. V12
14. V13
15. V14
16. V15
17. V16
18. V17
19. V18
20. V19
21. V20
22. V21
23. V22
24. V23
25. V24
26. V25
27. V26
28. V27
29. V28
30. Amount
31. Class
============================================================
Total Columns: 31

#### Preview Raw Data

In [7]:
# ============================================================
# Raw Dataset Preview
# ============================================================

print("First 5 Transactions")
print("=" * 60)

display(header_df)

First 5 Transactions
============================================================

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

#### Dataset Shape

In [8]:
# ============================================================
# Dataset Row Count
# ============================================================

print("Counting Dataset Rows")
print("=" * 60)

row_count = 0

for chunk in pd.read_csv(
    RAW_DATA_PATH,
    usecols=["Class"],
    chunksize=50_000
):
    row_count += len(chunk)

print(f"Total Transactions : {row_count:,}")
print(f"Total Features     : {len(header_df.columns) - 1}")
print(f"Target Column      : Class")

Counting Dataset Rows
============================================================
Total Transactions : 284,807
Total Features     : 30
Target Column      : Class

#### Load Full Dataset Efficiently

In [9]:
# ============================================================
# Full Dataset Loading
# ============================================================

print("Loading Full Dataset...")
print("=" * 60)

# Memory-efficient dtypes
dtype_map = {
    "Time": "float32",
    "Amount": "float32",
    "Class": "int8"
}

# PCA-transformed features
for column in header_df.columns:
    if column.startswith("V"):
        dtype_map[column] = "float32"

df = pd.read_csv(
    RAW_DATA_PATH,
    dtype=dtype_map
)

print("✓ Dataset loaded successfully")
print("=" * 60)
print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]}")

Loading Full Dataset...
============================================================
✓ Dataset loaded successfully
============================================================
Rows    : 284,807
Columns : 31

#### Dataset Shape Verification

In [10]:
# ============================================================
# Shape Verification
# ============================================================

EXPECTED_ROWS = 284_807
EXPECTED_COLUMNS = 31

print("Dataset Shape Verification")
print("=" * 60)

print(f"Actual Rows       : {df.shape[0]:,}")
print(f"Expected Rows     : {EXPECTED_ROWS:,}")

print(f"Actual Columns    : {df.shape[1]}")
print(f"Expected Columns  : {EXPECTED_COLUMNS}")

if df.shape == (EXPECTED_ROWS, EXPECTED_COLUMNS):
    print("\n✓ Dataset shape validation PASSED")
else:
    print("\n⚠ Dataset shape differs from expected dimensions")

Dataset Shape Verification
============================================================
Actual Rows       : 284,807
Expected Rows     : 284,807
Actual Columns    : 31
Expected Columns  : 31

✓ Dataset shape validation PASSED

#### Data Types

In [11]:
# ============================================================
# Data Type Inspection
# ============================================================

print("Data Types")
print("=" * 60)

display(
    pd.DataFrame({
        "Column": df.columns,
        "Data_Type": df.dtypes.astype(str).values
    })
)

Data Types
============================================================

    Column Data_Type
0     Time   float32
1       V1   float32
2       V2   float32
3       V3   float32
4       V4   float32
5       V5   float32
6       V6   float32
7       V7   float32
8       V8   float32
9       V9   float32
10     V10   float32
11     V11   float32
12     V12   float32
13     V13   float32
14     V14   float32
15     V15   float32
16     V16   float32
17     V17   float32
18     V18   float32
19     V19   float32
20     V20   float32
21     V21   float32
22     V22   float32
23     V23   float32
24     V24   float32
25     V25   float32
26     V26   float32
27     V27   float32
28     V28   float32
29  Amount   float32
30   Class      int8

#### Missing Values

In [12]:
# ============================================================
# Missing Value Analysis
# ============================================================

missing_values = df.isnull().sum()

missing_report = pd.DataFrame({
    "Column": missing_values.index,
    "Missing_Count": missing_values.values,
})

missing_report["Missing_Percentage"] = (
    missing_report["Missing_Count"]
    / len(df)
    * 100
)

missing_report = missing_report.sort_values(
    by="Missing_Count",
    ascending=False
)

print("Missing Value Analysis")
print("=" * 60)

display(missing_report)

if missing_values.sum() == 0:
    print("✓ No missing values detected")
else:
    print("⚠ Missing values detected")

Missing Value Analysis
============================================================

    Column  Missing_Count  Missing_Percentage
0     Time              0                 0.0
1       V1              0                 0.0
2       V2              0                 0.0
3       V3              0                 0.0
4       V4              0                 0.0
5       V5              0                 0.0
6       V6              0                 0.0
7       V7              0                 0.0
8       V8              0                 0.0
9       V9              0                 0.0
10     V10              0                 0.0
11     V11              0                 0.0
12     V12              0                 0.0
13     V13              0                 0.0
14     V14              0                 0.0
15     V15              0                 0.0
16     V16              0                 0.0
17     V17              0                 0.0
18     V18              0                 0.0
19     V19              0                 0.0
20     V20              0                 0.0
21     V21              0                 0.0
22     V22              0                 0.0
23     V23              0                 0.0
24     V24              0                 0.0
25     V25              0                 0.0
26     V26              0                 0.0
27     V27              0                 0.0
28     V28              0                 0.0
29  Amount              0                 0.0
30   Class              0                 0.0

✓ No missing values detected

#### Duplicate Transactions

In [13]:
# ============================================================
# Duplicate Transaction Analysis
# ============================================================

duplicate_count = df.duplicated().sum()

print("Duplicate Transaction Analysis")
print("=" * 60)
print(f"Duplicate Rows : {duplicate_count:,}")

if duplicate_count == 0:
    print("✓ No duplicate rows detected")
else:
    print("⚠ Duplicate rows detected")

Duplicate Transaction Analysis
============================================================
Duplicate Rows : 1,081
⚠ Duplicate rows detected

#### Target Validation

In [14]:
# ============================================================
# Target Variable Validation
# ============================================================

TARGET_COLUMN = "Class"

unique_target_values = sorted(
    df[TARGET_COLUMN].unique().tolist()
)

print("Target Variable Validation")
print("=" * 60)

print(f"Target Column : {TARGET_COLUMN}")
print(f"Unique Values : {unique_target_values}")

expected_classes = {0, 1}

if set(unique_target_values) == expected_classes:
    print("✓ Target values validation PASSED")
else:
    print("⚠ Unexpected target values detected")

Target Variable Validation
============================================================
Target Column : Class
Unique Values : [0, 1]
✓ Target values validation PASSED

#### Class Distribution

In [15]:
# ============================================================
# Fraud Class Distribution
# ============================================================

class_counts = df[TARGET_COLUMN].value_counts().sort_index()

class_distribution = pd.DataFrame({
    "Class": class_counts.index,
    "Transaction_Count": class_counts.values
})

class_distribution["Percentage"] = (
    class_distribution["Transaction_Count"]
    / len(df)
    * 100
)

class_distribution["Label"] = class_distribution["Class"].map({
    0: "Legitimate",
    1: "Fraud"
})

print("Transaction Class Distribution")
print("=" * 60)

display(class_distribution)

Transaction Class Distribution
============================================================

   Class  Transaction_Count  Percentage       Label
0      0             284315   99.827251  Legitimate
1      1                492    0.172749       Fraud

#### Fraud Statistics

In [16]:
# ============================================================
# Fraud Statistics
# ============================================================

legitimate_count = int((df["Class"] == 0).sum())
fraud_count = int((df["Class"] == 1).sum())

fraud_rate = fraud_count / len(df) * 100

print("Fraud Statistics")
print("=" * 60)

print(f"Total Transactions : {len(df):,}")
print(f"Legitimate        : {legitimate_count:,}")
print(f"Fraudulent        : {fraud_count:,}")
print(f"Fraud Rate        : {fraud_rate:.4f}%")
print(f"Legitimate Rate    : {100 - fraud_rate:.4f}%")

Fraud Statistics
============================================================
Total Transactions : 284,807
Legitimate        : 284,315
Fraudulent        : 492
Fraud Rate        : 0.1727%
Legitimate Rate    : 99.8273%

#### Amount Validation

In [17]:
# ============================================================
# Transaction Amount Validation
# ============================================================

amount_statistics = df["Amount"].describe()

print("Transaction Amount Statistics")
print("=" * 60)

display(amount_statistics.to_frame(name="Amount"))

Transaction Amount Statistics
============================================================

              Amount
count  284807.000000
mean       88.349617
std       250.120117
min         0.000000
25%         5.600000
50%        22.000000
75%        77.165001
max     25691.160156

#### Time Validation

In [18]:
# ============================================================
# Transaction Time Validation
# ============================================================

time_statistics = df["Time"].describe()

print("Transaction Time Statistics")
print("=" * 60)

display(time_statistics.to_frame(name="Time"))

Transaction Time Statistics
============================================================

                Time
count  284807.000000
mean    94813.859375
std     47488.144531
min         0.000000
25%     54201.500000
50%     84692.000000
75%    139320.500000
max    172792.000000

#### Memory Usage

In [19]:
# ============================================================
# Memory Usage Analysis
# ============================================================

memory_usage_mb = (
    df.memory_usage(deep=True).sum()
    / (1024 ** 2)
)

print("Memory Usage")
print("=" * 60)
print(f"DataFrame Memory : {memory_usage_mb:.2f} MB")

Memory Usage
============================================================
DataFrame Memory : 32.87 MB

#### Feature Summary

In [20]:
# ============================================================
# Feature Summary
# ============================================================

feature_summary = pd.DataFrame({
    "Feature": df.columns,
    "Data_Type": df.dtypes.astype(str).values,
    "Missing": df.isnull().sum().values,
    "Unique_Values": df.nunique().values
})

print("Feature Summary")
print("=" * 60)

display(feature_summary)

Feature Summary
============================================================

   Feature Data_Type  Missing  Unique_Values
0     Time   float32        0         124592
1       V1   float32        0         274338
2       V2   float32        0         275163
3       V3   float32        0         275081
4       V4   float32        0         275143
5       V5   float32        0         275223
6       V6   float32        0         275092
7       V7   float32        0         275182
8       V8   float32        0         275244
9       V9   float32        0         275208
10     V10   float32        0         275175
11     V11   float32        0         275043
12     V12   float32        0         275162
13     V13   float32        0         275167
14     V14   float32        0         275238
15     V15   float32        0         275134
16     V16   float32        0         275149
17     V17   float32        0         275148
18     V18   float32        0         275208
19     V19   float32        0         275185
20     V20   float32        0         275185
21     V21   float32        0         275170
22     V22   float32        0         275096
23     V23   float32        0         275186
24     V24   float32        0         275113
25     V25   float32        0         275091
26     V26   float32        0         275146
27     V27   float32        0         275295
28     V28   float32        0         275249
29  Amount   float32        0          32767
30   Class      int8        0              2

#### Create Representative Sample

In [21]:
# ============================================================
# Representative Sample Dataset
# ============================================================

SAMPLE_PATH = SAMPLE_DATA_DIR / "sample_transactions.csv"

fraud_sample = df[df["Class"] == 1]

legitimate_sample = df[df["Class"] == 0].sample(
    n=min(9_508, legitimate_count),
    random_state=42
)

sample_df = pd.concat(
    [fraud_sample, legitimate_sample],
    axis=0
).sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

sample_df.to_csv(
    SAMPLE_PATH,
    index=False
)

print("Representative Sample Created")
print("=" * 60)
print(f"Sample Path : {SAMPLE_PATH}")
print(f"Sample Rows : {len(sample_df):,}")
print(f"Fraud Rows  : {(sample_df['Class'] == 1).sum():,}")
print(f"Legit Rows  : {(sample_df['Class'] == 0).sum():,}")

Representative Sample Created
============================================================
Sample Path : C:\Users\viqua\Desktop\FinGuard AI\Dataset\Sample\sample_transactions.csv
Sample Rows : 10,000
Fraud Rows  : 492
Legit Rows  : 9,508

#### Sample Verification

In [22]:
# ============================================================
# Sample Dataset Verification
# ============================================================

sample_check = pd.read_csv(SAMPLE_PATH)

print("Sample Dataset Verification")
print("=" * 60)

print(f"Rows    : {sample_check.shape[0]:,}")
print(f"Columns : {sample_check.shape[1]}")
print(f"Fraud   : {(sample_check['Class'] == 1).sum():,}")
print(f"Legit   : {(sample_check['Class'] == 0).sum():,}")

display(sample_check.head())

Sample Dataset Verification
============================================================
Rows    : 10,000
Columns : 31
Fraud   : 492
Legit   : 9,508

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,81072.0,0.152504,-0.529875,1.176964,-1.202292,-0.797599,0.360677,-0.748678,0.153178,-2.342317,...,-0.257429,-0.426723,-0.139358,-0.987510,0.172512,0.135781,0.012291,-0.062251,26.00,0
1,32563.0,-2.198490,1.111433,0.962725,2.770526,0.265426,1.730794,-0.505490,-2.987673,-1.322962,...,3.052520,-0.083206,0.490815,-0.266094,-0.420221,0.340255,0.667370,-0.063418,136.90,0
2,27304.0,-3.532802,-2.228579,-0.903098,3.380612,0.658313,0.899873,1.017552,0.481798,-1.527926,...,0.135297,-0.083653,-0.024973,-1.254693,-0.267784,0.246260,0.618960,-0.047699,526.19,0
3,82271.0,1.253673,0.100741,-0.198298,1.077423,0.457483,0.596458,-0.006270,0.114836,0.501890,...,-0.199677,-0.377854,-0.230479,-1.340867,0.822117,-0.223347,0.032285,0.000885,12.99,0
4,141715.0,-0.186972,1.083575,-0.393382,1.096913,1.929655,-0.722338,1.385346,-0.378026,-0.594949,...,0.004281,0.254329,-0.353016,0.470720,0.165008,-0.405060,0.004793,-0.023925,1.00,0

#### Data Loading Summary

In [23]:
# ============================================================
# Final Data Loading Summary
# ============================================================

print("=" * 70)
print("FIN GUARD AI — DATA LOADING SUMMARY")
print("=" * 70)

print(f"✓ Raw Dataset       : {RAW_DATA_PATH.name}")
print(f"✓ Total Transactions: {len(df):,}")
print(f"✓ Total Columns     : {df.shape[1]}")
print(f"✓ Fraud Cases       : {fraud_count:,}")
print(f"✓ Fraud Rate        : {fraud_rate:.4f}%")
print(f"✓ Missing Values    : {int(df.isnull().sum().sum()):,}")
print(f"✓ Duplicate Rows    : {duplicate_count:,}")
print(f"✓ Memory Usage      : {memory_usage_mb:.2f} MB")
print(f"✓ Sample Dataset    : {SAMPLE_PATH.name}")

print("=" * 70)
print("✓ NOTEBOOK 01 DATA LOADING COMPLETED")
print("=" * 70)

======================================================================
FIN GUARD AI — DATA LOADING SUMMARY
======================================================================
✓ Raw Dataset       : creditcard.csv
✓ Total Transactions: 284,807
✓ Total Columns     : 31
✓ Fraud Cases       : 492
✓ Fraud Rate        : 0.1727%
✓ Missing Values    : 0
✓ Duplicate Rows    : 1,081
✓ Memory Usage      : 32.87 MB
✓ Sample Dataset    : sample_transactions.csv
======================================================================
✓ NOTEBOOK 01 DATA LOADING COMPLETED
======================================================================

#### 🔜 Next Stage

#### Notebook 02 — Exploratory Data Analysis

The next notebook will investigate:

- Dataset distribution
- Fraud vs legitimate transactions
- Transaction amount behavior
- Temporal transaction patterns
- Feature distributions
- Correlation analysis
- Outlier analysis
- Fraud-specific patterns
- Class imbalance visualization
- Advanced statistical insights

##### Important

The raw dataset will remain unchanged.

All transformations will begin in the preprocessing stage.